---
pool: 
  name: 'Azure pipelines'
  VmImage: ubuntu-latest

trigger:
  - efficient-webjars

steps: 
- task: Maven@3
  inputs:
    mavenPOMFile: 'pom.xml'  
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkVersionOption: '1.17'
    