---
pool: 'azure pipelines'

trigger:
  - efficient-webjars

steps: 
- task: Maven@3
  inputs:
    mavenPOMFile: 'pom.xml'  
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: '1.7'
    