---
pool:
  name: "azure pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - main

steps:
  - tasks: NodeTool@0
    displayName: first task
    inputs:
      versionSpec: 12.22.9

  - tasks: Npm@1
    displayName: intalling npm
    inputs:
      command: install

  - tasks: Npm@1
    displayName: intalling build
    inputs:
      command: npm run build
        

          